import {
  AlertTriangle,
  BarChart2,
  Bell,
  Brain,
  Building2,
  CheckCircle2,
  CheckSquare,
  Clock,
  Cpu,
  DatabaseBackup,
  DollarSign,
  ExternalLink,
  Gauge,
  HeartPulse,
  HelpCircle,
  Hourglass,
  Info,
  LayoutDashboard,
  LogOut,
  Megaphone,
  MessageSquare,
  MoreHorizontal,
  Package,
  Plug,
  Repeat,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  TrendingDown,
  TrendingUp,
  Users,
  UsersRound,
  Wifi,
  WifiOff,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconRegistry = {
  AlertTriangle,
  BarChart2,
  Bell,
  Brain,
  Building2,
  CheckCircle2,
  CheckSquare,
  Clock,
  Cpu,
  DatabaseBackup,
  DollarSign,
  ExternalLink,
  Gauge,
  HeartPulse,
  HelpCircle,
  Hourglass,
  Info,
  LayoutDashboard,
  LogOut,
  Megaphone,
  MessageSquare,
  MoreHorizontal,
  Package,
  Plug,
  Repeat,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  TrendingDown,
  TrendingUp,
  Users,
  UsersRound,
  Wifi,
  WifiOff,
  Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

export function getIcon(name: string): LucideIcon {
  const icon = iconRegistry[name as IconName];
  if (!icon) throw new Error(`Ícone não registrado no JSON: ${name}`);
  return icon;
}
